name: Ubuntu

# Trigger the workflow on push or pull requests for main and develop branches
on:
  push:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/ubuntu.yml'
  pull_request:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/ubuntu.yml'

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    # Define a matrix strategy to test multiple compiler and OS configurations
    strategy:
      # Continue running other matrix jobs even if one fails
      fail-fast: false
      matrix:
        include:
          [
            # GCC Versions (7-12)
            { pkgs: "gcc-7 g++-7", cc: gcc-7, cxx: g++-7, os: ubuntu-20.04 },
            { pkgs: "gcc-8 g++-8", cc: gcc-8, cxx: g++-8, os: ubuntu-20.04 },
            { pkgs: "gcc-9 g++-9", cc: gcc-9, cxx: g++-9, os: ubuntu-20.04 },
            { pkgs: "gcc-10 g++-10", cc: gcc-10, cxx: g++-10, os: ubuntu-latest },
            { pkgs: "gcc-11 g++-11", cc: gcc-11, cxx: g++-11, os: ubuntu-latest },
            { pkgs: "gcc-12 g++-12", cc: gcc-12, cxx: g++-12, os: ubuntu-latest },

            # Clang Versions (7-14)
            { pkgs: "clang-7 clang++-7", cc: clang-7, cxx: clang++-7, os: ubuntu-20.04 },
            { pkgs: "clang-8 clang++-8", cc: clang-8, cxx: clang++-8, os: ubuntu-20.04 },
            { pkgs: "clang-9 clang++-9", cc: clang-9, cxx: clang++-9, os: ubuntu-20.04 },
            { pkgs: "clang-10 clang++-10", cc: clang-10, cxx: clang++-10, os: ubuntu-20.04 },
            { pkgs: "clang-11 clang++-11", cc: clang-11, cxx: clang++-11, os: ubuntu-22.04 },
            { pkgs: "clang-12 clang++-12", cc: clang-12, cxx: clang++-12, os: ubuntu-22.04 },
            { pkgs: "clang-13 clang++-13", cc: clang-13, cxx: clang++-13, os: ubuntu-22.04 },
            { pkgs: "clang-14 clang++-14", cc: clang-14, cxx: clang++-14, os: ubuntu-22.04 }
          ]

    # Set environment variables for compiler executables
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install the required compiler and dependencies
    - name: Install Compiler Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.pkgs }}

    # Step 3: Configure the project using CMake
    - name: Configure Project
      run: |
        mkdir -p build               # Create the build directory
        cd build
        cmake -DCMAKE_C_COMPILER=${{ env.CC }} \
              -DCMAKE_CXX_COMPILER=${{ env.CXX }} \
              -DBUILD_TESTS=ON \
              -DWARNINGS_AS_ERRORS=ON ..

    # Step 4: Build the project using CMake
    - name: Build Project
      run: |
        cmake --build build --parallel 2   # Use 2 parallel threads to speed up builds

    # Step 5: Run tests using CTest
    - name: Run Tests
      run: |
        cd build
        ctest -C Debug --verbose           # Run tests in Debug mode with verbose output
