name: Windows

# Trigger the workflow on push or pull requests for main and develop branches
on:
  push:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/windows.yml'
  pull_request:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/windows.yml'

jobs:
  build:
    name: Build and Test (Windows)
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          [
            { cc: cl, cxx: cl, label: "MSVC" }, # MSVC Compiler
            { cc: gcc, cxx: g++, label: "MinGW GCC" } # MinGW GCC Compiler
          ]

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step: Install Dependencies
    - name: Install PDCurses
      run: |
        # Install PDCurses for Windows
        choco install pdcurses -y
        echo C:/tools/pdcurses/lib/pdcurses.lib >> %GITHUB_PATH%
        echo C:/tools/pdcurses/include >> %GITHUB_INCLUDE_PATH%

    # Step: Install MinGW for GCC support
    - name: Install MinGW (For GCC Support)
      if: matrix.cc == 'gcc'
      shell: cmd
      run: |
        choco install mingw -y
        echo C:\ProgramData\chocolatey\bin >> %GITHUB_PATH%

    # Step: Configure Project (Use Visual Studio generator for MSVC)
    - name: Configure Project
      shell: cmd
      run: |
        mkdir build
        cd build
        if "%CC%" == "cl" (
          cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_C_COMPILER=%CC% -DCMAKE_CXX_COMPILER=%CXX% -DBUILD_TESTS=ON -DWARNINGS_AS_ERRORS=ON ..
        ) else (
          cmake -DCMAKE_C_COMPILER=%CC% -DCMAKE_CXX_COMPILER=%CXX% -DBUILD_TESTS=ON -DWARNINGS_AS_ERRORS=ON ..
        )

    # Step: Build Project
    - name: Build Project
      shell: cmd
      run: |
        cd build
        if "%CC%" == "cl" (
          cmake --build . --config Debug --parallel 2
        ) else (
          cmake --build . --parallel 2
        )

    # Step: Run Tests
    - name: Run Tests
      shell: cmd
      run: |
        cd build
        ctest -C Debug --verbose
